---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins # Name of the HelmRelease resource
  namespace: ci-cd-system
spec:
  interval: 1m
  chart:
    spec:
      chart: chaos-mesh
      version: "0.0.0"
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
  values:
    rbac:
      create: true

    timezone: "America/Denver"

    dashboard:
      # Enable dashboard
      enabled: true

      rootUrl: "https://chaos-mesh.${SECRET_DOMAIN}"

      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: simple-icons:grafana
        hostName: &host "chaos-mesh.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host

      persistentVolume:
        enabled: true
        storageClassName: local-path
        size: 5Gi
