---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: ci-cd-system
spec:
  interval: 1m
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    checkDeprecation: true
    podAnnotations:
      secret.reloader.stakater.com/reload: cluster-user-auth
    crds:
      enabled: true
    networkPolicy:
      create: false
    metrics:
      enabled: true
    ## Install Default RBAC roles and bindings
    rbac:
      create: true
      readSecrets: false


    controller:
      # Used for label app.kubernetes.io/component
      componentName: "jenkins-controller"
      image: "jenkins/jenkins"

    agent:
      enabled: true
      namespace: ci-cd-system
      image: "	jenkins/inbound-agent"

