---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins # Name of the HelmRelease resource
  namespace: ci-cd-system
spec:
  interval: 1m
  chart:
    spec:
      chart: jenkins
      version: 4.8.2
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
  values:
    controller:
      # Used for label app.kubernetes.io/component
      componentName: "jenkins-controller"
      image: "jenkins/jenkins"
      servicePort: 8080
      targetPort: 8080
      numExecutors: 5

      # This values should not be changed unless you use your custom image of jenkins or any devired from. If you want to use
      # Cloudbees Jenkins Distribution docker, you should set jenkinsHome: "/var/cloudbees-jenkins-distribution"
      jenkinsHome: "/var/jenkins_home"

      # List of plugins to be install during Jenkins controller start
      installPlugins:
        - kubernetes:4054.v2da_8e2794884
        - workflow-aggregator:596.v8c21c963d92d
        - git:5.2.0
        - configuration-as-code:1714.v09593e830cfa
      # additionalPlugins: []
        # - instance-identity:185.v303dc7c645f9
        # - docker-pipeline:572.v950f58993843
        # - theme-manager:215.vc1ff18d67920
        # - discord-notifier:241.v448b_ccd0c0d6

      # Set to false to download the minimum required version of all dependencies.
      installLatestPlugins: true

      jenkinsUrlProtocol: "https"
      jenkinsUrl: "https://jenkins.${SECRET_DOMAIN}"

      resources:
        requests:
          cpu: "50m"
          memory: "256Mi"
        limits:
          cpu: "2000m"
          memory: "4096Mi"

      # Name of default cloud configuration.
      cloudName: "home-kubernetes"

      JCasC:
        defaultConfig: true
        configScripts:
          welcome-message: |
            jenkins:
              systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.


      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: simple-icons:grafana
        hostName: &host "jenkins.${SECRET_DOMAIN}"
        tls:
          - hosts:
            - *host

    agent:
      enabled: true
      podTemplates:
        # Python
        - name: python
          label: jenkins-python
          serviceAccount: jenkins
          containers:
            - name: python
              image: python:3
              command: "/bin/sh -c"
              args: "cat"
              ttyEnabled: true
              privileged: true
              resourceRequestCpu: "400m"
              resourceRequestMemory: "512Mi"
              resourceLimitCpu: "1"
              resourceLimitMemory: "1024Mi"


    persistence:
      enabled: true
      storageClass: local-path

    prometheus:
      enabled: true

    rbac:
      create: true
      readSecrets: true

