---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-apps-jenkins
  namespace: ci-cd-system
spec:
    interval: 1m
    chart:
      spec:
        chart: jenkins
        sourceRef:
          kind: HelmRepository
          name: jenkins
          namespace: flux-system
    maxHistory: 2
    install:
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    values:
      checkDeprecation: true

      controller:
        # Used for label app.kubernetes.io/component
        componentName: "jenkins-controller"
        image: "jenkins/jenkins"

      ingress:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:kubernetes
        hosts:
          - &host "jenkins.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
