---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: ci-cd-system
spec:
  interval: 1m
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    checkDeprecation: true
    podAnnotations:
      secret.reloader.stakater.com/reload: cluster-user-auth
    crds:
      enabled: true
    networkPolicy:
      create: false
    metrics:
      enabled: true
    ## Install Default RBAC roles and bindings
    rbac:
      create: true
      readSecrets: false

    serviceAccount:
      create: true

    controller:
      # Used for label app.kubernetes.io/component
      componentName: "jenkins-controller"
      image: "jenkins/jenkins"
      servicePort: 8080
      targetPort: 8080
      agentListenerEnabled: true
      agentListenerPort: 50000

      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "jenkins.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

      resources:
        requests:
          cpu: "50m"
          memory: "256Mi"
        limits:
          cpu: "2000m"
          memory: "4096Mi"

      jenkinsHome: "/var/jenkins_home"
      # This values should not be changed unless you use your custom image of jenkins or any devired from. If you want to use
      # Cloudbees Jenkins Distribution docker, you should set jenkinsRef: "/usr/share/cloudbees-jenkins-distribution/ref"
      jenkinsRef: "/usr/share/jenkins/ref"
      # Path to the jenkins war file which is used by jenkins-plugin-cli.
      jenkinsWar: "/usr/share/jenkins/jenkins.war"

    agent:
      enabled: true
      namespace: ci-cd-system
      image: "	jenkins/inbound-agent"
      workingDir: "/home/jenkins/agent"

