---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: ci-cd-system
spec:
  interval: 1m
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
  values:
    checkDeprecation: true
    podAnnotations:
      secret.reloader.stakater.com/reload: cluster-user-auth
    crds:
      enabled: true
    networkPolicy:
      create: false
    metrics:
      enabled: true
    ## Install Default RBAC roles and bindings
    rbac:
      create: true
      readSecrets: false


    serviceAccount:
      create: true

    controller:
      # Used for label app.kubernetes.io/component
      componentName: "jenkins-controller"
      image: "jenkins/jenkins"
      servicePort: 8080
      targetPort: 8080
      agentListenerEnabled: true
      agentListenerPort: 50000
      jenkinsHome: "/var/jenkins_home"
      workspaceVolume:
        enabled: true
        size: 10Gi
        storageClass: local-path
        accessMode: ReadWriteOnce
        mountPath: /var/jenkins_home
        subPath: jenkins_home
        subPathExpr: ""
        volumes:
          - name: jenkins-home
            persistentVolumeClaim:
              claimName: jenkins-home
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "jenkins.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
      resources:
        requests:
          cpu: "50m"
          memory: "256Mi"
        limits:
          cpu: "2000m"
          memory: "4096Mi"

    agent:
      enabled: true
      namespace: ci-cd-system
      image: "	jenkins/inbound-agent"
      resources:
        requests:
          cpu: "512m"
          memory: "512Mi"
          # ephemeralStorage:
        limits:
          cpu: "512m"
          memory: "512Mi"
          # ephemeralStorage:

