---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: ci-cd-system
spec:
  interval: 1m
  chart:
    spec:
      chart: jenkins
      version: 4.8.2
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
  values:
    controller:
      # Used for label app.kubernetes.io/component
      componentName: "jenkins-controller"
      image: "jenkins/jenkins"

      # Name of default cloud configuration.
      cloudName: "home-kubernetes"

      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: simple-icons:grafana
        hosts:
          - &host "jenkins.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host

    persistence:
      enabled: false
      storageClass: local-path
      accessMode: "ReadWriteOnce"
      size: "10Gi"

    ## Install Default RBAC roles and bindings
    rbac:
      create: true
      readSecrets: false

