apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: discord
  namespace: flux-system
spec:
  summary: "Discord notification"
  eventMetadata:
    cluster: "*"
  providerRef:
      name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
