apiVersion: v1
kind: Secret
metadata:
    name: discord-notifier-secret
    namespace: default
stringData:
    config.toml: ENC[AES256_GCM,data:fzNbDMwzkOMUkqhRoYBi7qp6EGtVxyiDvCkUgJRCOlvBHxVGZTaluL/SsBK1+KaO1YP6+ZWGKUIkLn6x6LEutYKdnDTNRT8rQevBbW1e2vobomYFmxw6JroaOHRI7MsBni/kIKeV9qIMAlXttN0yPF+BZA0yRtzAkZK/ljM5c7Mo+pDr7NiiT+BtTPJFQnXKXVgTIBcuKGlNgZe3+cUzgv/Gq+FbH6w69K8FBrM4H5B+HKMir2FDM4KfQBPtBbupPJGZXozSqK9LxziKbj9KLyH7ueWoFlX0sqfLmiZZI3yi5ByhxkA70BBqlu5fFcivoytgE967oZW9WgouxgebpCDt+7/b8AtlOPbphkd5P1Yg6u1xhlHwVtNJlL4tcIlf,iv:a5ZluA5JumIZaV+4fJ92oUMAxfCIPWYLQFI7EoV0JGo=,tag:ZJ9AKx9d9xa+1OW1yOI9Qg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1a3htKzRNRmROK2hNamFK
            bkNJQnRXSTN0TmttOHl2dmRmd2JZazdnd3g0ClkrQ3BaMDgxN0M2OWN1YXRFc0k5
            MXZES01SOVR5N1NBTUhkTHZrMWVjZGMKLS0tIDZzVHc1ditLZXR5b0VaeDJiaE9i
            L2tnaVhHbkpRWXNNcVQ0WjVpdHZvZW8Kfz7KDEebpdK0bMpTMT3as+P62rR9dkEz
            JG4oIj8j5Fmyjs1GzgYOmtHeYo9WHJtwH018fRMgYkGbCNtoA31pAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T08:15:17Z"
    mac: ENC[AES256_GCM,data:T0zuGhz0e23c4h0vURNMmsxHGYoPV/exlnzCM5lqQpdSIA3YuEvxiahIgTi7wjdHogvYuVxeLj/xcJajkiH+L8xJ+Qs3EYgc8vVohXqQ2PR4++/clYlPPR5iT/mn9oQuCYKb0l7G6lrLoTFPPsV42l/3Y+I+JQAt3SG1+PEOYvk=,iv:KKRGn7oRiveTEpqAL09aRj+JTztTc4iQzpWXp+8r6BU=,tag:dKpdIPYhqeyMzsc6aMiwrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
