apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
    namespace: default
stringData:
    config.toml: ENC[AES256_GCM,data:R3w6GayB12MQ23tPkw9tsryRxlv8UxDmZy8m9gMeeO1DEqqNhKova2feahWzYA1AlOd44NGOH+VbodcwYBos5mCIAHJKJwwHNE83viFTIhoiUKD2yLpx+XjdUN/77XaD98kki85R1/Q4a/tu9XjfcWkf0gTwIBW9ZE2azbeDKk8OX3QYYV2+aTz+uYsKIV0t/c8Aw9JSBazTRICTG3oATVt3cLd0s4eQrsnYUFJrJ43IhtnXrBojmDEFKwEF94QIu9UAJbHk9HOHyV0X1tLh17QG0WKUbMTeRef7FnpAhsviGMaz/dzxkwgnq7ADb57zonYIQ5u1sVTtVnKU0Pdl/8lhytrBOSI+NGUxJEw/e4bYGAKpx5DFHV1hftXgC+g2,iv:UXdSjyv+RTz+zlV+Pzf3ZMcWzNbodQ4Fr8gz0FWducY=,tag:0TmzcrNlgo6vLwoxvf995w==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudDcxNE9pWVRhVUxHZ2o4
            aEFUMHNLTy9ybjcrOGRncnpsbUwrUDRYWGpjCnVoRmhpYTVCaVlXNXBPZDVOdkts
            SEswTFBFK0pyNGtkbkE2cmRhVzFETzQKLS0tIDVYNFljUU1HbTY3OXJIa2JxaUhX
            aXhrajNYM0twby9RN0RIUHF5TVNMZk0KkUfG5EgIem40Ex6SYSxrzYIxQzGnZM1k
            ZgMDKkLL9y+ouqtRk6UlP/M8QgCjI2JmVViTa69zC7C1dObCGbyoqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T13:59:34Z"
    mac: ENC[AES256_GCM,data:H/cfNc/pt3Lib7p/TRkYi6ymfmzao/E3HqoChqBVcMbOAgBKmKB6+5oJyZtr29+cXWQn+pzsK/OKXlHJR4s3vmlGvJ5y0nHtKqPbX9Ws5k6ABQdJo5RN69/ums/I6VZ2avqNR4JgeP5AIgrOJISvdnrwJSzHqlEOsRDR9iOyfGs=,iv:tjLGT9CptglpoIvt+KKaFGbEdeOh3TjGGm3EEIq9Cbk=,tag:WUdYgMgnb3779clocxPA3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
