apiVersion: v1
kind: Secret
metadata:
    name: discord-notifier-secret
    namespace: default
stringData:
    config.toml: ENC[AES256_GCM,data:kpsT5ivpJvbeW394Gzy6Ajdsu8/Q0R9e99MbZaeCpl/nUJnLLuERUeaE/uf+zBrfuV13Hf2/yHyzM9K6zXPtaAdkslxPG1nf2QitCcHKIxosOXd6tRN5UrkDzJVX7bY1dyI/u3GhocyW7o0fL+9JBJmYb00jOWvw0oMOW9BW0INUsOnwkBWu5rmwXHBVygdFpEjIu+VM0mqzHeUHi7T1kB4Ilz/szhOkZuJTcW/HXpsxl7SroQlrwMz3Zp4oBYB38fWtCM/yenRvBJ7SGcFL/Mtc21UBQTsNGdUJv9eWBDPsJeh7mM1GksYZB3UvbC5V1b+q5N+HPuZL+YWO8SaVmIC4sY/vadLQ+WqHFZEYIebbFGcSKUr09OwTKZr6pK2x,iv:W6CBjqN1MVCe3lTroefeFMPEGhHNvlYVoRiGpH6igfI=,tag:RT2ZIb9F2ORY+3+dO1q6Cg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSVpwQnJOUm03Y2NoN1Vm
            ZzhMVXUrUmI1bDdnbE1DeEcvV1VROHFMMWxjCk9ZdTQ2L1o1Y3ZNYjJkZTZnNTNm
            d0tqR3BqSDZEaHd1bTh3L2cwOG9mZncKLS0tIHRNS3ptU29BY0JLN01uME1OajMr
            ZC90aUlRM2g0VGJZQkdmQkZmbWhFWHcKbxdOCIPleGIL8HvmkFtT+rUuGrSKXvGF
            k+gmDYudYoP38W25Pwi5BwugOrwzOryKu3PSU8Yk0WbcxOL+p4mUGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T11:06:13Z"
    mac: ENC[AES256_GCM,data:WfYCYQPwJJisSSHzYHUNAmTtrBj5C3e7JFGtNnI3hj4V/oP5RtR+Sa23EPj80KhesXS+qPq34lEF/29/GE1KbH5DEqcQfG7D/ojmodCFlgYTw+T6CuWr8bfHLgvvCS+lu9hCzpBDzWWY0ChXxfEQbK70XleLaZbHR86zX+gGFWs=,iv:jgeb3uozqFs/zmNAYmBUPES9jASRdwSXo4uiSa5bK+E=,tag:AS1vFPc29b/b/ufmvj6/4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
