apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: helix-elastic-agent
  namespace: helix-ai-app
spec:
  version: 8.11.1
  elasticsearchRefs:
    - name: helix-elasticsearch
  mode: fleet
  fleetServerEnabled: true
  policyID: eck-fleet-server
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
