apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: helix-enterprise-search
  namespace: helix-ai-app
spec:
  version: 8.11.1
  count: 1
  elasticsearchRef:
    name: helix-elasticsearch
