---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: helix
spec:
  interval: 30m
  chart:
    spec:
      chart: eck-operator
      version: 2.x
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # replicaCount is the number of operator pods to run.
    replicaCount: 1
