apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: helix-kibana
  namespace: helix-ai-app
spec:
  version: 8.11.1
  count: 1
  elasticsearchRef:
    name: helix-elasticsearch
    namespace: helix-ai-app
  podTemplate:
    spec:
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: simple-icons:kibana
        hostName: &host "kibana.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host

  http:
    service:
      spec:
        type: ClusterIP


    tls:
      selfSignedCertificate:
        subjectAltNames:
          - dns: 'kibana.${SECRET_DOMAIN}'
