apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: helix-kibana
  namespace: helix-ai-app
spec:
  version: 8.11.1
  count: 1 # INFO: leave at 3
  elasticsearchRef:
    name: helix-elasticsearch
    namespace: helix-ai-app

  config:
    xpack.fleet.agents.elasticsearch.hosts: ["https://helix-elasticsearch-es-http.helix-ai-app.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://helix-fleet-server.helix-ai-app.svc:8220"]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        namespace: 'helix-ai-app'
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: fleet_server-1
            id: fleet_server-1
            package:
              name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        namespace: 'helix-ai-app'
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        is_default: true
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system

  podTemplate:
    spec:
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: simple-icons:kibana
        hostName: &host "kibana.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host

  http:
    service:
      spec:
        type: ClusterIP


    tls:
      selfSignedCertificate:
        subjectAltNames:
          - dns: 'kibana.${SECRET_DOMAIN}'
