apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: helix-elasticsearch
  namespace: helix
spec:
  version: 8.11.1
  nodeSets:
    - name: masters
      count: 3
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: standard
      config:
        node.roles: [ "master" ]
        xpack.ml.enabled: true
    - name: data
      count: 5
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 6Gi
            storageClassName: standard
      config:
        node.roles: [ "data", "ingest", "ml", "transform" ]

