apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: helix-elasticsearch
  namespace: helix
spec:
  version: 8.11.1
  nodeSets:
    - name: masters
      count: 3
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms1g -Xmx1g"
          persistentVolumeClaim:
            storageClassName: local-path
            resources:
              requests:
                storage: 1Gi
      config:
        node.roles: [ "master" ]
        xpack.ml.enabled: true
    - name: data
      count: 10
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms1g -Xmx1g"
          persistentVolumeClaim:
            storageClassName: local-path
            resources:
              requests:
                storage: 2Gi
      config:
        node.roles: [ "data", "ingest", "ml", "transform" ]

