ansible_become_pass: ENC[AES256_GCM,data:9czK9+7ShUQ=,iv:lM9TRgTxghqWq1qwXor8Q84lhVRYE/trIn++J0RLwIQ=,tag:PUNos5i9wGfyFRxwMqXtcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMUpSZzgrQkhpRzNVTklv
            WUdDQWRteDUzQTFvbVhtSE5UV3VNSjFHS2lJCmdFOG03WklMT3ZYYUtRME9UMzRy
            R0FLaU9zZ2FnQWZyWG82YzRGWXRzMVkKLS0tIHB3Y2JUWWJQUklaaG5TZ2JzZ0Rk
            VDFIVEY3TUkrVG1GQVJGS0dLeTFFeDQKMBSE6O5qkPyPJC2j3DZLYtyKrfxTPLHY
            bQmBhcSH/97l4CazOQ3LY3pgbK/AzPiXH6AISZyZ7qwXLHyCu04yzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T07:41:46Z"
    mac: ENC[AES256_GCM,data:93hO21ZO0/hiwEyop/V3g8WGOBI06zW9/tmgftJB/19HwdCBxQ2FmyMTFJK/F2AthVlCOZ6AwsUlMwt/q6owdg2EZxs3fFjYmqBwnWwX7AN7G4OJKYtrs8kqTC6Sw4h6sthqzQUunbGrO7FAg0iBqFMmnMeLTPl6BAZ0gqDneAQ=,iv:keOznrUL58079h39qzbvQgDYwXtkrdjTpxky3D6EwzE=,tag:NHcehqY4pWE2OgIFiY1zQw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
