ansible_become_pass: ENC[AES256_GCM,data:xq7HkS1FjIk=,iv:1XlgLmGsqls/Sc9q4N2sGCLWZAalq01hWI8bISk2MKc=,tag:BsJT4PoH6Lq2OwCuC3M6cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SmpLOGFmbEJKUjBrdDdQ
            ZzJoM3d5UUFHZzdGQkxoL1o3OTFPZzZoUUVzCjE4ZlZ6ZzFxWTYxVXBsTGdZRVhM
            Vy9wY3NUZEtPNFVDQXB5UDlTenYvdGsKLS0tIDkwMXMwcEdiY3dHNVlzNjUyUXpu
            dCtCd0kwQU83SVY1TnIzWHpPZzZBM3cKKSiEFmAaRV2+OcY0VvzOf3MTIJGNvNUJ
            jrff07Sc6mYwLLzdWw7IKRPg3yWk8U2auvJFtiDjsh/p1BQ2w87OzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T10:09:14Z"
    mac: ENC[AES256_GCM,data:b6V3KFLyPSkMAZsZFLrxSPK8pDCMPbKewPGf1gUruP8Aer87UMg2D9RXZKajg8JXjNAcqr1Svyroey5UwDB9OdvNzMGnFgC3S+vaFtFVn7eCYgmZV9IyCTOQPdQfnVVEkccChDbjCl7sl4PLBr0nJjVs09MWzCvZv1CgAj6aCNg=,iv:GRi7Scv2htNqUOQEfQe6hvXRyUF+KkIzN8ZAmGUQ22s=,tag:1VLk2LBPXVAwleNQf+e38w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
