ansible_become_pass: ENC[AES256_GCM,data:887T+55hFQU=,iv:1qkBrVXaWw7mVaXUmWWUF8AfKp4pHQqBrI2JWbIRN04=,tag:nCgx+p/PGDzjJlOQAg1+wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QThtSUpvdVNUZllreVNF
            R0lhM0tHM1pkM0F0eGZnM0hVQnBHMTBVdEJ3Ck5mNUwxTy9BekdkZFh0V3E5ajBV
            SUNWMHFNY3pod1l2S1NXdUNQZFhpYTgKLS0tIFpQaVBUTlBBM1IxZG0yK0VCVXY3
            Mlh3OXJRa3pGQ2RNcm4ya1RqRHB5cUUKnrtTZlGjOPQd+n0RODgz3PrdN5mmV+R+
            wafQfIma7HUAZFkthtNavQ5Xb92gnu989M/gUSLIG5dW3OkxYMUaAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T09:36:27Z"
    mac: ENC[AES256_GCM,data:/vtOTj3ih3gwxw8HRJ3y9k2mJuQM/XA9vEhFzvsM0f83FLYNSdP1FZjrDfVDLt8ur89uMn7hZ43dC8b+M5xkr5zsD7Hs6H22F4BJOPeGKPosCvfgMCKNRQjkky3jyyK/VRLhJrePDt+qRY/Kl99X9SLy0xJxV7Q+8FkY5f9lAJU=,iv:C7SyVLBrIJBWXm/zJyWfygNIyH4v5xX1gE1qql16z/c=,tag:8KNp38LuU0xF5sXdyej4ng==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
