ansible_become_pass: ENC[AES256_GCM,data:TpZEDLRNs4A=,iv:39sCxnsIXa1jc5TDneurt6MARzWdjWUDFcOqFqr26jQ=,tag:gg8j+H9RTjm8rWeglv4aWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOGIzUU9uanN4YkMrcmNB
            bkZxSmFTVXhrckJJY1VYQmYvc0xmaWhJNWtrCk90R29DWEcxWkUwcDVKZHlVSmx0
            NUM0V0lSRzc0MzhuQVVCcE5sT00zdWcKLS0tIDB4MFF5TlpPTDQ1eVppbTB6SXRG
            MjhFSEwzVmtoMWs2d3FVdkR1bGVNUVkK29XzrKc0MTSiWs45CiXnYscdpo9QZvsY
            qlY5RTmV0hNzBbJTtj/Af/9ZgMbFUtPy45kKmkCPiAuJ2k/ZJaLkgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T14:07:08Z"
    mac: ENC[AES256_GCM,data:YYk3+8P5aF0L8ivpzrnLMor0nkuDV3WI3hRX73ND/HybpyBZumkwSIqfRsmk6QOnLXpgcnb4iNIB0O1Bvk4kuyaLQp/7JChzmyPtdvZK7shyDCySoUxzFM7/ja6pt1Bme7JfDlYMbjTfjwXJJWmXHbMy7C7tFJst7Ggy/AIKEWo=,iv:+sXTmUgpVx/b2GIVE/pS7zR71KM89b/ULmIJhVM6nK8=,tag:ZgQqHCpCFyq1WkSLl9CRBg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
