ansible_become_pass: ENC[AES256_GCM,data:DN4KkleYjAY=,iv:evUXz5F+etBRT/jE0UzePN07CmfAaDqmsfPe6luP85w=,tag:6DC9dggV/vbiZvG/SGpS1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcllwZlN5RHlaaElKU055
            WjJqYVUzR2Y4a21WeHUzQVlYZTY5ZzlFS3owCjh6LzFOZHQrQkRmeWpGaklBL251
            NG5lMzhWQVFPS1lsRDh5cXBVd25ockEKLS0tIHhrbXd2TElaRm9ZeVEyWExESDgx
            SXo3aHBLeHl2cjhMb0M5enltc010VVkK/yf3lDwnnZb0eOSWYCRRPh8twzgngiTE
            x2vVQdpEkM/wwc3HW2sY3htYLZfMp3SgxSa96+xbTX0DTNTxxs1c9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T11:04:15Z"
    mac: ENC[AES256_GCM,data:sYhvkdLEB3wRZ9ekKPp9G1WY1sSaagBsCNwZxs0qsq6RJrYHToz5/AY57Fd6ZscV4Kl0pUCaiMGkBmrRnaoGcjP0hmLAmXAUOY8DeN40t0Zkf58kAB66kZou4O2QoKMU6Arv/c5sNZUhPITYMGBSHb3STiMjcS4dsQzy98Zsflg=,iv:qwK0uHy82nQu6zNuLy3mMDtiAjQFZep1MM4Y8rVGgZk=,tag:eeYfUuyYMQvwxSO0IJ47eQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
