ansible_become_pass: ENC[AES256_GCM,data:K5AgSffNh4Q=,iv:kGC/273Y3Z6Z1o3rBAGmnzJ1EPAnaW8VjqPkBHulU2o=,tag:B9kPIdnjM58DmHH3ar0wCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZGVkMzk2bzlHdVl5MVV5
            d2ZvaXhBdGRkUzBpQjYwUk4xK1ljcUY0MEZRCkFGWlA3ZFpkR3B5cjB0ZFZsRXRU
            a2pwVllxUUJsTUZMKzJMT2NHeGJaSE0KLS0tIFlwSlU1bkFiZ1diUko3aTZ4L3ds
            eENvSC8zMXdXaHFzV2ZTeHZwNmhkSW8KiOcmWvt/Bg8KTfuN3XRiZeaDTBYszEZC
            D1Ii3HLySVL84OhxcUDYUusrC8VOQp6P7r/E4n6CE1MEC96tsbzSKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T07:28:40Z"
    mac: ENC[AES256_GCM,data:AsDABPmnp9A8bKM5YLsWWDVStdDD1A307EEeRNFXmAxEwwuzKC3SXUNxmbviwPgfaOrN4McUyXQj0wpKRepDOdhPreRWju4KEdqqLwXRG81/mWR4m71HQLXUFbEYItI1wRCLDeCHQTSIFgIdoSX19VgnDoeFVXqHnZr4SGMQj5s=,iv:4n/nQg1gB8qqh4rI2HsxLknQPA2OyDTA0WwfUuxmLVs=,tag:A2HwB/OMF/Ir3X0w9E7pzA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
