ansible_become_pass: ENC[AES256_GCM,data:YfWUeVPT/64=,iv:DWT2HUG0k8g8+0TPGfDEAVtKQEKEb63emggyAAEEAdM=,tag:ASInlfjqGu+IHj4OjLzp/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFd1RCSjBYcXQzV1EwQkpu
            TUo0K0tSR09VYTVqb0VZUXVKZEcxdG1EZ3lNClp6T3creFIza3ZaTmJmeXB3aytT
            cGQ2NzRDWnpmZS9KRWRZakJkUlY0c2sKLS0tIC9sNWNqcU5iMmgxMS8xZnFvWVpy
            ZVNkQXBuL1R5L2VHL1FjMHk5ZUxMYkUK4lQIM+tIoCuklL4mgFmtFMNIr95bybWW
            yn+CyX/bwIGukdnEN6uxgT/mVTXdADEfoSP47SBsgbeUac+Ri5dMoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T09:36:27Z"
    mac: ENC[AES256_GCM,data:GgeLkolsCk25LldL2wf4NNARTZ3lWGOu4W4EZrjGsHScFCk1E6Y6HvXR+7fCpMtz+X22VIBZlMfa08h35b12/RXKI7iDYARgTzH24ffjY2uqmohy0UvOk4TunpGnQMnYvBSmlFyJ1bl5a/i2nuhOU3/zG0wz8nUjABq2T5t/Jf4=,iv:uSaTQ88oOiA7bclHebVyQjWBjITPgN6YbpMFDmDRkE4=,tag:lehQTKuxUn3zw8H8fv3d0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
