ansible_become_pass: ENC[AES256_GCM,data:aJGEMlW3kZE=,iv:5o4MyMwk/iUzVYaQiJi9KxZCsAWjwCr/FPRqShZjEVI=,tag:ucxFQw1UcNYPQ+WSIW4I6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBON0RJNGJ6endac0ZqNVVr
            dFg4aDlOWXJFOGVmcm1SK3BVM1F1Z2E5RWxnClN3NlVROU41WGtrUEFSRFlJeW91
            QzJZejMxZ3gyZDdrVHFPUlFrelV0N0kKLS0tIEtNRHRJYWdBS1NpM082bUYrOVpM
            cnBhK3JKcGxMdm8vL1BVbFA3SjhLV1UKoJQUp/Ixnqv6cny5QW79jil8PMFWwPmd
            fkQFYxQZeEimpB865rvWyOpw9cN0YoeNGn7+wpOkwMFAXtbFPRSZGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T11:16:28Z"
    mac: ENC[AES256_GCM,data:BnqezUV+k+nfITjuzGYWcUOWlyaPuc89kQLqE1FgCAYNxdaCqNG09fgmcn+slna8HfvkzR53vayY7VBlXfYa8V4rgAVPvznyPbOy1JNewxfs5MPgVE9H4N26mAIBVLPt0j7JbciVAYKCdoGLXCR9MNYyhjkmLcdckQz6kqGSMs4=,iv:uQUNAVw4nW2qekuQeHWriUzbh0M9CFgfg8ct7LGdvB8=,tag:3mNXEoCZYdqt1zJdcIha1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
