ansible_become_pass: ENC[AES256_GCM,data:1JyrixA3Tb8=,iv:niP0opKPVALmhNLdqpN0N8VRKHro6kTquuPj1/GbYv8=,tag:XoMRgD7TjktJzolO2DngaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKd1J2ZUNGVys4amRrT09R
            QjdFdkxlTGpIVWg5NGNEdEE2c2hHNVdzY3lVClJZTStRVXpYMGdVUTRuMmJLeDdP
            K1J2V0RWM0FOam0yc0JMc3BpNWdBUnMKLS0tIGRVOE5URUVXNmZmcDNjQlhkQVRD
            bDJtUVVNVjBvZjBJNmdPNWcwa3YyZmcK6brlP/lY2ITAqM1/eZibwMhbJMRFEEj+
            feASs8WeVAQw03FjwVW8ArUr5twMujoVCTNDedl6gUJQzyd5YLCQEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T09:41:02Z"
    mac: ENC[AES256_GCM,data:ZMkSXDC8Ryp+BZqOrXdxKYMn8g+tSpOjDXRFWnhwkONiWff+MrFwNSPFVZYyZvFXZhs82v7BNbfnECU0KW8Fo0csNtuJOazUeiR8NpDhWIwRMVvaQMsql5QkQ5Y9Fwi94YK35lZTyCuuTX5948XYOMjqEHhya6Vo6GIzrAHN7DA=,iv:fdx9K1n18YjEmZj/pOPa/cFsj3b/O2tt17EecnO9daA=,tag:0JEbF3MUV9bvf9l+tkeaRg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
