ansible_become_pass: ENC[AES256_GCM,data:hPOcfNrAnCQ=,iv:nqWy/sQReiiY8aHYrG8U3fd0mreu2NRkGUzbQayP7yI=,tag:jaE3OJYXcCJ3f0cRuUv13Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQmo3d0gwS1ZUanBFUlhz
            VVNYL2V3M1hWMy9qcU1IV0wvc0pSL29xQWtRCnNid25KZ2l4a3dteUxVSVFOckFC
            Q3pWekVQSFYxRW1DbTlpN1JMUUw1djAKLS0tIGoxV1NRdGRSK3AvUi9ZSUhBSXR2
            NFdWMFREUlRPL1YwMmlIVVFNQXNWNW8KB8dR9FgOXhZhyBoMI+LehnE+AraGnFPU
            Dbpcy/jUfygtPg2t6/mmXg3ZrNEDfIPbpsElWfDeL2eKfznU/f/dEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T08:13:11Z"
    mac: ENC[AES256_GCM,data:+hE04nsftjqRO9XCe+30DnH/VbyTjqmOKDhDoStDOfsDPG/d+0PjcJ6LL6ckLzDFZukyYeqZUGw91S8JQa8zjepqkEoBuUJ2Rt0Vu0Wl49gbQ0F6YJPXjVUFOYcFZKvI9M607qoDL1lZn6W2obf+z2bOY2yYUjOT+W6GFzaPQA4=,iv:JFOcY6PqoHFRa65Yi7QuN5VzsSCIv0Zeh9VnMnwAtAA=,tag:xR8SHEkP3jX9SeydLP01UQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
