ansible_become_pass: ENC[AES256_GCM,data:TMhQVY2MPM8=,iv:CW+yfGPskFRGViX3mmXT21MFyx2j2wAFubXMjSq3Fr8=,tag:sdoS7ZeLEQfLGuG9d3ZIKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VzNBNzNvUm1MaE1ZYU9s
            ZXNWaWxPY0N2RElqSlg3ZGJhb0tGcW1EVlNZCnFsQVF4OE9UN0Q1aFVkVSt5VEZ3
            bUNxRDB1VklHQ3dRVXpjVXZRaWJrS2MKLS0tIGprWS9xZGRRRVprMTZUekx0d0RZ
            YngxVFJDSzNValRIVm9Bbk8rNm1UbG8KBcQBtwKAhgRRw2l4Px6JdQQ/AO+gw7Sg
            neey846PcEt7ohaQu3y5suWMzdTxDczB7kQMRs3vCuSNkfEi5BcPlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T10:30:16Z"
    mac: ENC[AES256_GCM,data:ColCPI/2y8T1nPvSru57VgqkNEK7ryBzFTZQnJemgGlYkM56ORK58jCKYJEMWlTutbs5p/uYPPH+dEhLRATDuLfXPIOejH3QYTFA2FLUUVukpzWZUG+BNdJir0PCUNTYw78zjg15hppln1EK/QpJA5Fgh8of0+96ppm8Tm+8BZU=,iv:wFRF5/jFKxIOZMQGvt5nTPpvsZskLo7OMoQnwiUbpjs=,tag:G9ud+C5UYlGXw4BIBxjSfA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
