ansible_become_pass: ENC[AES256_GCM,data:k8vRT0SpMvw=,iv:0cPB8lbFnjxbVNQi1G4QwJKT+KDn8Hd7zvzWHjR597Q=,tag:mq4Gjmn+5dTqKnezZbyjdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUmNVWkRzWjR4MUgrUVJF
            S2JpRjNva0hDYTlNcEdaeU5UQU8xNWRBdkV3Cm5TcG5JWTJxUzNTTW1yaEQya1Ny
            ZDJWZXljS1hGMVUwdVpGWVBCOU5QVFkKLS0tIHZVczhycVZxVkdRZzEwcUFLSG84
            S3VvanB1Vm9LT2ZpZ21KWTAwK2dZVkUKeiZRBh+CbSov9+eDcTQWZPO/jSkxBhde
            BL8o4xWktUm7Z+XzowIU0Ugw+Kq97xqDaKdb0zjRYAp2OR7Tzc+Scg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T11:16:29Z"
    mac: ENC[AES256_GCM,data:j/YEUANs+NjP3anaN6TY3OiyzDoRLXb6tuDbHQf4IpVY97uQJzjB9tANsFr04NVvyz4JPirNA+RjOtHy3ma8uSWYaN1EC1I1PzyyRz8yXkHpt35cJbfFAn/LnRYElc9sk5WHkqz0dZX+z0OwqLDbPt/SKAxGgS5wOzGVIYouEEs=,iv:Wo10UmLlQnF8ux0eveVAGDTD+pPWeabb18Jn5q822Oc=,tag:Cc8Ytp7ctId0R5y+Dn4seg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
