ansible_become_pass: ENC[AES256_GCM,data:TQyqdE63E5A=,iv:PrPwGyhBJUC63N6p3sbQ/uqM5NNphiwgZ8IwUZ7zRS4=,tag:klueh/S+HvzsC0DROJ83YQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWCtPMDFGN2ttdExhQ1V3
            OWRGSnNucFB1TmFkNitKQXF0NmdoMDRRazJFCmFKL1ZRc0I1MGptUU53NmFuSFpT
            NjNmM3hpdk51YVA5UW4zZnFwRTc0YTQKLS0tIHhOV3JKcGtnYkVIVWpTMWQ0VHZq
            cllVaWNkWlBXV3NYaUFjdGFtMW56QU0Ks89dcCH4FQpO3BHQBeRaIWUKg9V1xnoW
            nBad5GY80f1/p5WSSAFEubUMsssYMDgj6DAT+JPDJOT4AKx3gT3Snw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T09:41:01Z"
    mac: ENC[AES256_GCM,data:HdPpAHlQ2RAwDzHZ53QhgQKJLKlpgP4cfFgkNfSWOfoDciWoI9eZ+dmFoy7qeguC7Zoi2iSOkJE1Atg1B2bCew0rVERkm3j1OwK+lMFk6oBL/obV7Fxnn6mbWsb9gjDFSuyfvLGIFo8XJ22cs76ikkSS8pXPRK0sFMyquZ6qnBQ=,iv:kwXXcwKbTi0hASaBIFz32b18mrd4xZ53VwSBHyiQ/A0=,tag:3gbVlQ7I7IfKnNO+lFIz/Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
