ansible_become_pass: ENC[AES256_GCM,data:5VPEjBa/ZSY=,iv:GhYiKNrs4XvWOdxgZWXojSZPYv55lmLMtVydSHRVGeI=,tag:AcTzPjew4IC+pbjfW5pwEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUjV0M0IreDRNL2Q3MVNH
            WnBiaUJ3cmR3SzFwWUlBbkxhY1NtRmVTWDA0CmRpWTlUYXpPd0YrNWQ3dFBtWG1X
            emtzdURLcGMzTEttRE9TU2FQZ0ROZ3MKLS0tIFRpUFFrbXlqUkVRV0xnZnhUTlR5
            bVJxNlU5WjRzME5qUTcyRWVMeDRndUEKVGJoYRMuI95b+Gd9cbd2I+7okuC/nwAp
            QlKJy0O1LaUX0YfqlrlyhY16wuYJgMw+ZPiJN1yTNnZ6uMtuG5ooTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T08:13:11Z"
    mac: ENC[AES256_GCM,data:Dn2M6DoLdHw+jU2Bfy1nv4ZXLfEeTr4rXQfUwo5auh77aoVWOZIFA6437xExUFQLe792fGsIJJOYjnZ3yVoyVfZRvZvrQybhCtlbyhwSbIpoJWdUe/nS6iZdQeGc9qbYKuqmgsUs89nS5TVOCYjNaZkJ52UL90l99qNvtv3BTjk=,iv:vKQyIVpXpYsrjLP7T1Z+ejJ4ohrZi1I4Si3dhJGYLV8=,tag:Z+OPMl5/mkRJ5IDygBPjFQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
