ansible_become_pass: ENC[AES256_GCM,data:Ytw7sym+Ks4=,iv:Lrrnb9v1irBKWNy/S6CGvb6QKVi1CiaFxYeol1tyyVs=,tag:oT88GFt0nTyTtd4NNp99XA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dk9t24upsxd5zqs84t5l69m9fvzze9e7t7mm5n99d4tkr8whqacqpcjpgx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZ1Awd2hFOHNyQXBrY0Q0
            WGZubVVxWTV6cGVRR05DSTN5a3oyeXZudUJzCk9uWlZ2OXllMWRhOUdoU1RuSlVj
            RGRwRytXMkJESk04RWpDcXMyZDFKZDgKLS0tIHdHZzNVbGEwbGhYUTEvT0hlRUdu
            KzV5QmVMa0FxNk9pZUp3bGR2MG80UHMKbPmZqqGS9lXFRrxYW2XfrN/o7oyULzK+
            4adfosNMx216fJKIR3DcRBFicmo2z8GyNuBT3Wo2c/Eq6We0HtY/HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T17:10:07Z"
    mac: ENC[AES256_GCM,data:v8iUfzY8Tv/BUM/TJcnZwe7L51/LQVBQCOCa2ppspM1OoezcSdCfI3Eg1UFvbzjQOey3jUMYQ6CwTXaRSjqos/aq5g3uHe3AiOvDCqeEqVfXcDBsp1qgSTzhPb8oq3Pm6VY+7e59y0adZib71ChfkwF3kvH2jSR07p4iXvCipMk=,iv:YhtqVs3cIBdrlKJm3l8mezR+B6KYwPMyZpubryMxSr4=,tag:dryrgk+SOyaqOHz1vE89wg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
