ansible_become_pass: ENC[AES256_GCM,data:cKAhf7b4b/4=,iv:h1wGraR7v1LBGzQFq+ZApOF0o1353QPw+E02aOBEydQ=,tag:DZjiDcdFV0Ny8mfWJncD/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RC9EVGxjeWJPZmwvbERa
            alk0TE94NlgwR1pFNUgvTHJJQW5MYUdTcDJFCit0ZFh1S2ozWFBuK0hmS1JJVVVZ
            Vzl0QkZGTjVORkRrVVJpRldZWGVDbHcKLS0tIHJ4bTN0bHVVeXFiNGQ3dGxidWVO
            dWFQOG1IUW1xcDMzRDhOR0ZCRlZrUEUKlRzOBZQ2XTxM9s8mLIqyjjeeklBN+5sI
            RhPNO1di0aQ5sc1gA4/ZFmjI6feXf7bOkmlhLAynG14UIFiYfQBDEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T10:09:14Z"
    mac: ENC[AES256_GCM,data:8u2EpxSn5peM1a7zquE/gyEQwqMLIqqvwaSJjgik7u74z5Ry/yYYS/4xnihuLCx4QBg662OwnO4afj0WJjXjHTPoDW3XmWmG/eSkzRkExI3IFu1hIgqgpV/iq6hW3Aj9aDH1eXN9WYjLcp8gzk72JppfqbF89x1RA2Fk/wkyfi4=,iv:UCrmOwB2T6kdSKjkZxXUhRO3amim1l7x3tr623EGGkI=,tag:6VwQG9Vi722rmWBLbY4E8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
