ansible_become_pass: ENC[AES256_GCM,data:T0GJwUrKKuo=,iv:oZiqfwjS8OcNHZDS1syYhi+pA19FjuxPQzZxc1P9mUo=,tag:Q/udJLi0Axy402ma22ViOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdU95RzFEbnF5ZEdGekIy
            Q21FTHJWQnEwczE1aVJwb2JBQ3p1SXBNQ3g0Cld0dG5GUEkwdmlYZW1SUkoyMEFY
            SkVsQXlsZGZXSDIxcVFlTFl4WUVncVUKLS0tIE4wRUNMWVdaQU03bVVBdHFxWVlo
            RGp0eFR0Z2hkMHZnM1VKRVpsY2x6WkUK8c+O5ZsfplDtLc7f/Sq3LBFfjGPhHsVj
            3msUcci4wEIzwWKsJhyztErhRTlfrWwtiv59Qav5gWPN3Z63CCkYBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-19T20:38:31Z"
    mac: ENC[AES256_GCM,data:ef/nEanVLiPEYmrpPFAqV338uknYKjxUZsCjLpLhCwIakYo7/aB0MHw3lEtcooc7zjgZMLv7ilmo0G5JDEHIyPykIZZoxH6b/d6kJPWGlF3F3tJr2PVHqPEq4js79TSKbeDEGtPmuAiSozzuGEyBSejPpAhFM9ft9OAIZvwkBgI=,iv:mdi4xJuJf3oP+xURsnVEj38Mw5OUsleQp90MG7sO+yI=,tag:2R0V2q/ZwrGOQfd67MNvmg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
