---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: flagger-system
spec:
  interval: 1h
  releaseName: flagger
  maxHistory: 2
  install: # override existing Flagger CRDs
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade: # update Flagger CRDs
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  chart:
    spec:
      chart: flagger
      version: 1.34.0 # update Flagger to the latest minor version
      interval: 30m # scan for new versions every six hours
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
  values:
    nodeSelector:
      kubernetes.io/os: linux
