apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:J+QnZYug0+gqwVi5oCQ=,iv:A4tfF3rk3pYS6oaUe/uR5YbUbY/fZ0pG4F2j27Lb0q4=,tag:HUcrXXuvgCYKpg6W/jAQEQ==,type:str]
    admin-user: ENC[AES256_GCM,data:cMx1PyE=,iv:OnV+MK18KaA5+dP12ylrECZqohsuri+ISNDL+BJ5eoA=,tag:qRJBqZICKekUxw2PCkG2Nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUmNqS1VidTlVcU5rVGUz
            dDBwYTVZeXRxU2RWWEg5dWhndTB1Y3R3T0NrCjExdUQ2V2lhZjM1c1ZyK3lwR2Nx
            bVI2ZTVBTDFMRU95enRTVXQwSHN5ZW8KLS0tIFg0OVF3L1ZPU0hZK2l5amNGNE56
            R01scVV6M2RvMG1yTU13RU1OZ0ViRlEKGsDuUBKEcfwZDa9A0iPxxMY4WNn2zHXF
            wmRIt4lyKLsnFUugs5CdA8tTBy5BpTTe0NLuo9xzEu+7GjNrKdZbZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-19T20:40:06Z"
    mac: ENC[AES256_GCM,data:2xGgg3rUdFcUtRYPfDPaNAZtDOmfbS7JLFakrET1KXUTN8h/aQY0haxuEepYWKpob/eplpPNUrerpKkNfxLaoS7Cq7dTuf4sANevuY/dtCXA0CDHRBvjmVakx2hZqH4grG2M1rChsHsdkbu+WsomH8V4FRcm3OgjBttHJH37odA=,iv:Y/v7hNmbHewzRNwsG//Wy1yi3PIQBqEtFZj4v/hpa0s=,tag:6vquF/V2ocDzRmDqqRc68g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
