apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:B4PiEshCVr2SlQMl9nY1Mt+VrTu8DeuL,iv:fpzUqyKnwxRquhlVB2JIKwLlmFny8b+bQV1m+R2bv1k=,tag:bnpx4bXOZKkd3uArB1qacg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUXA0eGFOM0xLRjh4ZkE2
            bVY5ODNOZlhWSXpuMjJhQXMrb3FLSWVTdVNRCk1aUUZYYUZ5S3hzd1NkTW9VWmFU
            YUtqRElqazc4RFo4MUZheTZ0U0l5ZmsKLS0tIGxlYjI1OFQxRzZ0ZXJDL2c4UEJn
            bkUrYkoybW1LYmZ1L3B1WWZFSTlDWlkKPCugGC+gRq40pZoAjPpJ+mnbQh7UVFuE
            2g5d3kew40bnLaecn/qzhuK6axB0QeOHjLprb7C4yT5rA0boduM96A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T15:49:57Z"
    mac: ENC[AES256_GCM,data:gaXKHeSyIFGQf7f1ibRHLqy185ue8vPt0eYUta8VnYu4XmTmZx3FPiV/VG4YPPNSCB/jtYmdX5+eLPQohAd8FLwBi3JgipUmlwP+luIjHG7Y17AACnsTlMpHZmuZ5Hih9ySkJ4awl3DcHKWobCeKQJO2+euf0DKbld+SiFVtJYs=,iv:fjzv5MauLw+a3eKALJpWuVX2wP//uf32YK2MeqO9lrc=,tag:DRArQPCYUhggXSkYFk1sHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
