apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Yu4nUE97KOu3B8shQlfh+JtVhs2x+fE4,iv:OdQUdUBA6/SaO7bEbbSeFWH+8mX+2oyi86/v1F63Ros=,tag:bHgwmphatE0AB5l5P2U3SA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbEp6N2g1R01VSjdpZ0U1
            UW4xWmJCV0p4UmdwNHZ0WmNGcUZ6QmJZaVRrCm1UR3djZDA1RVJxVXJYdW1iQXBk
            dTNMK0wrKzRrWDdCNVV6OHlrdDk1U0kKLS0tIDVidlVZdTFMbDRFejJVdXdNbkY0
            eGlsWHVjZzljTFRwekRHQ2tZS0JmZm8K2Wh29BJpUOl8ki9rA4Ko3jYJsG/4tT9L
            J7Dt8nvOQxndbddr8k1CpE9JAT4ExPOFwrjrVGelwiuhXFldiAsKYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T14:08:51Z"
    mac: ENC[AES256_GCM,data:Hkj+k2iMcj26FOx+2nVzDSmVtSCSy42RKfykhalau7N45EuAc4MiyUuYc7NV+DND8KfnTojUx7PgFVTu76dop/5rWPa/6axagBG4jQ/nZ9aPRAnPbv6yp6Qdznq/uLzwTLkJN/D43fkidiYPVbRb6PSXj0ytdTzQhiFGiaHG6do=,iv:pNTe9h2JONfe3XGczpWOsGDQYN3IDgmQYvFG/dVXV58=,tag:BImEmjnC+PsvAaLoPHqpNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
