apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:4o6T9qN9h23F+aPXhsw2cFGCku1wjRNI,iv:4x6dpFrxLK8ACCGyVATwCq+xLYNnSJpHSaxIwhQ+GgQ=,tag:PLzkVixu9n0UK8H5/iCVfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QWFxV3Q2YnRheGdPR3NS
            d1dzWjNwKzVvc0JLSFZqU2R4UFdhSWd5cW4wCkJpMGt6VGZZS1h5bDBwcDVZLzM2
            cXFraklKdjh6dmlhY0VjOVdjT0NZK28KLS0tIHpueWhFY2tqUU5TUEJ2NGpTVjVC
            dXRtUm5YbXpjeFJXTEVsYitSQi9EL00KnRaA/zYlWOEezn8kbASVMD269MdQ76mq
            o/TaN0Tq0/yXoEz4zqhLy1B8B7Tc4OjTpyyh9BImdnYTbYoRbwmGLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T10:10:50Z"
    mac: ENC[AES256_GCM,data:lykzzXHcf4asfwq2Y3Gs6AojZBK0q8HzFHhYkvPnkm560WuV606XF5seioiar4FrV4yN2WHZR3jLK6MZRbV6iYB1qwsqkw5EMkLdaefxaAKLGaeBuK/JHhYN68eEwwyxUmJFA3xgIzlBTerdCCMHsJ1RAmyzin5oWdvNUMOeSoM=,iv:14lamHRkpPIDj5onmwf+8kV+ex13RWGEhsFXub3CV54=,tag:xHAKbP8wKa4oMS3I/llcZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
