apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:EPxkb0gNtJvkXYUiCIxxY5WVTVMCEUB5Op5LVM4qirBZefTVet0j2g==,iv:UZTxQyNkIikZh7orNeanWCHFSEwtnMH0EGVeDfldw3g=,tag:Oa9XHMjWIvK4RbL4hfjFZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUFRvam1QSTdpOExrQ251
            aW5XVWlsOFJ2bzNESC9SdmRmK3hweXZyZWhBClhBR1RNVTFvS3NhdmJhVmI2Y1U5
            WUpBbEwxQXRwQUlnWFhYWWhPQWVMY00KLS0tIHM2Y0x5Z0tmbkQvcnhkMlZiRVE5
            Nm9QbDBUL0ovZ1d1TVN3c2w1aExVRE0KS6CTkcragK+uLTOsZlyujLY5oTJBbD6R
            GuNLnQhNn8yHVUqg9PK4ebyYePc61ekvYCxhXo4YM29cbeO4+K3aZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T07:30:10Z"
    mac: ENC[AES256_GCM,data:1XMoUGIVXJK6L9COAK6GVTX867B7Q2JVkpGVTpgnMCrjGu3pHbQXVO2F7Z3T6BUeFCqZ+r7BvpS7yYW7LOnvOvikpF5Kx+Q84T7OsqdN6Oc19fujWqRkpJGwgmn+f1DXHMcgU5qjML2HvIkJ4hhT3NjuINw06qjXsnvv5i5dfkI=,iv:r8gfgmRPoelYvi2nFRt1IWUnuCCpAvIR6Zdrdvh2+nM=,tag:ciULe2gx9/0SL5jJ1uWo0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
