apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:uUZWpXv6sFZSL/jTS/rzps5u8kwBbf+ObVWPNsuAb1htyP97IMtGSg==,iv:UfOKe36BjYvVV7bBkpr0pYdxNnHo/dgkhZeynlL+iA4=,tag:x3/X8XWaI90JI3qVNFNLKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMFBZa2RrcDl0c2JGNDJG
            T21qY2JFRnlLSFlHOG8yWDFmSkhHWnpIWm1zCjdWWktpZW94YVJEQW9vMXFKczZC
            UXl6RGlzakhoZUJGMjZBaklLb2ExODQKLS0tIGJ5Q0FNa1F2Y3IvKzBFa1hmVFFw
            MHNGQTk3QUE0NitwZUdleXc1N25hTG8KcopS/RX2WTXiPbJYPGqVsPj6aJGwIAdj
            FrkvSa5ohgfwL4W4mbwb3ikEHtxc2GCkRZfI+q6uxl78jeUGFbEpLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T15:49:57Z"
    mac: ENC[AES256_GCM,data:zYIjv3vpXmvxDKxEdPNYS2BJVmrzB2ZkWBdjdeOFWIHLOC6PDIEOnZJnbEsj9W6MyZruSVLNy/vRPGuSZ6niZVCA9yYYB+s/23q5coKQoHqVTb97I++HH8kxE1MMaiY+1nUbMDdXTJHf/yVOHLeCla+h5lQHtHXQkRkMbBhea1I=,iv:oxUaxYYPAepQ0/q3qwVyU8BTm3sUPdk83R59wXT1/+E=,tag:e2FMpD7cPcxayK4YoupdEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
