---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-longhorn
  namespace: kube-system
spec:
    path: ./kubernetes/apps/kube-system/longhorn/app
    prune: true
    sourceRef:
      kind: GitRepository
      name: home-kubernetes
    interval: 30m
    retryInterval: 1m
    timeout: 5m
