apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:JIdcMkD4mEgne9RT4ZfVqBtFAIm/jV3Q3+5wSzsAuwLcUYKZzotgoQ==,iv:LuAh5N80KY7Gt4kcRZ/v2BlpvqX2fDb+/H1408Am3AU=,tag:E+Q+poHnxfW44xvNubVkAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1U3pjcURucXhTa2p1czNN
            ZzZUbEg2YUp3SE5oZUZmZFRPZ1hUMkVHMHpRClIwemRsZ1JBMnRtTmNjcW85b1l5
            aG9tZHJBMmJtRGU4Yk5OYWsvQkVkVkkKLS0tIFRtUUFoTW92YzlDY1lUczNDUWt0
            b2JhZ1VvdUdSYXEvSDlxMjJETUtCUUkK6/RF2NxpTtS+X/lwMat96jMnmBptrq8o
            ySssIkYFhButPv/NrJQOux6sM+1rxylydgwkvNqnrfDg2FpGhTLgNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T02:24:07Z"
    mac: ENC[AES256_GCM,data:1HU68DxI71AsnuJBvuAizvPGUshynkvCtTPxmOB0AJCBdEoe16u2AePNEdOiZOH2ZVRp4vKvId/si/bnToP2pdRoYfxxjcivL5gN1uTgfWCScqSozAAN+LB0Tjm8uM7UgJjZB8Fa6Bwc4x1HF7K4vB74RhbY9CZHGln+VUiZEzg=,iv:jj+5p4qe8WCxv2yp19Rbzi3nZmsRtUcsMu+6kGu+WFE=,tag:prkKZol/JtMfxI8fNnxd/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
