apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:TryKn3qAqpFvDInNp+FWVehEUpK/jg8xTxNc9Xu/ZyiXlIGmKJLtGA==,iv:2l1prOOW772XAdTvF45317i2z6943Ioo+H/puNTDua0=,tag:WSw1ZcBhhbVU2nyrvip/tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNWt3M3Irek91V2l6UklL
            aDBtUmVKODhKczBWMkUzMHJvUjBHQXhwWVZRCkZnYzg1WGJUWExyQWJZRFBUU0t3
            RnB2R0g2Q2hxN004TStDRUN3bDBwdDQKLS0tIEtkQTBMYy9zT2NSTHpaV0htR252
            WWdzV00ycmhIN25MK2hzV1ZLL2ErUUEKgY0tVYa0+EsZtJkxJ+jnJmzCqYKQdCiO
            0mvgkTXdOjIm+q9D4Nx2+n8U8K/psoVKfbcAWi4g2vslggH4JkVhGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T07:43:21Z"
    mac: ENC[AES256_GCM,data:mkyekH8oqBnWYJ2UFs0dlEbZnyo2yPTK/OZ4l/yHXTZiUmF05KkZlbzjS4rD/b5iVEkoWGsIbxbGBXJO4TpQ5ygCKK0QeZDybEaFuVBuGHhNhLUMfoCcWRzrRQEHRaqqN+CV18bp/zAYARjjLmp6M6dyBmrEkS32G+0ISvOh6OI=,iv:bZkwGQyOZGINC/5v1WNjD6I+724f/12+n40hxpNkeVg=,tag:iaW7npXeOHVDhqcSVjxq+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
