apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:GlssR5YsXC6l/fCg1Mmkw+FbmaRmYtGbfKez4B54gY/p0IQ25FNIIiIKd9kLUwcL1PP2iX0tRmWz5qHO,iv:YkmRGZrL4TEeRtqq0hdSe+WWNhrN16C8ft0APk4qg+4=,tag:y+XrqBvvR5S/zxq5xJHPXA==,type:str]
    username: ENC[AES256_GCM,data:UQdvBNU=,iv:qo35aaGVLezl+Dh66LlgyUGTVZKaGmcTSi+uamB05Yk=,tag:QzdgKAYofo2dLcjBr8BtHg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VG9wRmlVOGtvdWN2YS9w
            MExXd2Y4VEszVFNoRE5nZFZJdWxxdllCNmtNCk9KUmp1UE5GMHAycTRMSGVrK3pU
            WmpmK3hJdSsrNDRhc2RXTXhRNFJtUVkKLS0tIHNJeXdlZm9BVFBvaGxPbUVMdnlx
            OEYwWjRRUVU1amV0dVFCNlhKOUtqZU0KYxvPiLf/h6iqvDdy1LDjSbfHTK96ZGIW
            6s2w7kgBP8S4p81Zyd6NXnu9s1M71TjVXBYq4CH6D71RDvT6nNKzGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T11:18:24Z"
    mac: ENC[AES256_GCM,data:mlvpTzgD4ISZtWoGNCmgeDW/CsBNf88+uePKWw52t9x+XPex67nN70N2GoP1pf3WHC4pA6HU1xbac9ItDyFmWWJWP5pSZPVXto0bzoYoJTJ3KnVag3A0d3rJMNyEXWNZQBHNHysOHW8e1RpWwYmLtVGfgA0Gn1D1yuky3oOoZwY=,iv:yBSFNQX2cYC5tv3tHe6YWkWESO61SW5vsN63wNNJ/vA=,tag:/kJrfdA5hRKW7iP8PV4ZPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
