apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:v4T8IYuUiEsy1kTn4dR62oyWE32fgHcR2RIzHiKKqRrgOWlBbPwi2ZG8+OowHQl6EVUvZ0sZ5b/+wVah,iv:v/zggWrxagVVFog0P4G0SUyxFRAQGNfwWa8EjzxxgwU=,tag:aVWXGVvNCTdi6E/ZacvlOw==,type:str]
    username: ENC[AES256_GCM,data:YmNkFWc=,iv:jlHpiV8d4xCe37kad8lzNP6u9zK2h4QAsT8qpeA+vAs=,tag:XS6wnaR7e9+iwTfa6iLtyA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NzdKaVpEREFvQ296aG5y
            TGVrTGsyS0tuMnRsbWFValFVUlFQWHBaZzE4CnJOL1JmZk1xUU1mTGNNUDBrckhn
            eUhOc3dVb0U0QUVuU1NGSldBOGc4ekEKLS0tIC9zblM3OTJHaEh6dGsyZmF6R3Mx
            bml6RFBkY1o4TzFReng3RjZMQ0xjUk0KrjWo528je1LMSikJvPBCRaweV0TS7pRD
            xN7ITjQnwdGxYo2PTRd6ihO/2iRNg7KyEKCLtH8XrCFapVsDBJbwCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T14:09:17Z"
    mac: ENC[AES256_GCM,data:mBoBoGfpcF/Ca2lSdpecTKThZJ4fMGIoFYOLPkzYsqDcUykdue6G6+p3e61GHbC7nbv8JdLSlA01aOvrT8ptAKV1kUuX2hiv+B0R7uqjUnyfbW0nM1DTtb6R/B47Dvqb3xMoTke7hK+sp76aAixtchVy/Bup50r3gNdEwbdwpog=,iv:EOPF6Sv+E/qR6y+sMJLucGfK+ZvxT/WwIpb0uq28UIc=,tag:ram0Wnp0j1hANLc0/wT68w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
