apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:lOk=,iv:nCMSQzqbFfqzKhIqlN67daIyR68hNIugBMiJ9GWSAkk=,tag:c2It/4cNLbRCE7VT6yJEeQ==,type:str]
    username: ENC[AES256_GCM,data:IJutG1E=,iv:ybPUxDPvLJW+S0hTTSJN9WNRu/Qja42gwuT9gzjiWVE=,tag:EqnSW0Nf0RoD3SqYwM8jdg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreTROay9RNkhucDZYd1lk
            MWd3V3JyR2F6SlY1MU40ZldLbkxUQ2tsOWkwCkViRlZkY1R1ODVKcVprdjZ0d0xG
            V3pOVnBCNnhycFplRVV3dTcyckFFbHcKLS0tIEdqZjlXV0dxcG5PdUNNYnNGRis3
            UzR5UHhwYnh1QTBPRnRJUnNTMGtEWHMKJvBvjWZDFMkTasMjLGaqyHqyAfUJDkKg
            wHaHpF2+gc/m+eZbd03eGgnHauC7xcfVj4n6uR1TSniEkaG6XWzVQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-19T20:40:22Z"
    mac: ENC[AES256_GCM,data:IxBliuow1YA0s7msesdTi5fy3YBSsaGWwVZ0WcKifuSgyGkaA5qPlRzUVXRYmjDEDV5ajL56Bh6I5Up+swh/gsPKFKbSpLnb2+qGZzXpgpiwtCRhqMCfyxUIfFDgSR9ZqRyljc/gcVDtLnVYNfncPAOGd77wYYgHvZCj2SVOJz0=,iv:M53e+/9rcgIyZ+yccKmrkZSRG3sH2pPzs8XD27RYpnw=,tag:/S/Js5QdoAXagaGCr4V4RQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
