apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:CjoTjVUhna1Hn6j50ZNiK6aMg4BTuBUu3JrR/yBJ8Yj2zFNA3z9JaGL1n0WEEny8W7s0Fx0hD5ha+UYs,iv:l+nAXFNtxlFHRsbLzdA59JvsfVKqKqwIR9Q6lOGxXJU=,tag:nUyc56P2ZspYnWTOj8vchQ==,type:str]
    username: ENC[AES256_GCM,data:BGICmQw=,iv:A29+hLDpHxLyoxsSCqcC9HBV+AbOm+ey0B94iXH+6II=,tag:wgd0Dve4DeRuOrTIGk0gWQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRDgzaUtHeEpFQWZFUVpn
            S2ZrY3ZydmM4MUR1N0NNOEUrSndEbE9rNXo0CjFEd0RVb0xyMEVHOUJmZTkvUmwx
            cUlSdDFzSXBCTHg0N2VobjdEVW1rSjgKLS0tIE85SU1SUHNYSThKeFVWQnZTNGUw
            TlM2VWZLWDcvTmJHaUQrS0hCdUhsT3cKgOB/DUQzXnWUAx19zZdUiFvz6VRgTKes
            JJE3q2s8KxZjz2oG3QJBV9qAvhp5UMVjSfXCl6Jxgspg/KHgFYzqBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T15:50:19Z"
    mac: ENC[AES256_GCM,data:3/wjIEE0wXu6xQTmAvQ7MhEC5iycTVmoS0sFikf0lMXqd6dSxYRSYi+tKqbBwDsXKL/NlTebG4ScT/onUA4lvTE5kTWroVXVBxphMkOdc1CvI4ewo3Iqmhk01hID+pehq+y3ujMCgUVA9mFVxiThAGv3Kuw5f+TtADfRszyqixw=,iv:ELdx/jbY1QP+2ZiylnYVn+ViCo51gry3I1LB23utivo=,tag:G/3T4o8EUSqg6mK0XL1O7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
