apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
    type: discord
    channel: kubernetes-cluster-helix
    secretRef:
        name: discord-notifier-secret
        key: url
