---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord-notifier
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: discord-token-secret
  username: FluxCD
  channel: kubernetes-cluster-helix

