apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:I1s8dUnKJXufnMqbwdR2+hPZj27MEvY=,iv:K0/ulkQegvp3c6RBV/9ASI/jDPzSPzCjUZTVWT8uuXY=,tag:7ytCqfjBz/sYb3y2E3Yb6A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:v4NPoYtjQreFGbtIHP9WrgXleUMAo5s/HMMV9k5WTMAdi/5z,iv:YfGqnDF2flc7AmEpa5NS60bZJt059OUs0CwV39gOddU=,tag:TMOWJuEZsDq0tLqVqyx2uw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:aDA+FJrojzkLj5jPX0o=,iv:9gpa6SOKZE7+RhLwDfolJdzxpW7/gxy7YvIkfYnoDgM=,tag:WrQbI8XGfXsxsUcVOSqGHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ajRLelRRY2J5V1R0Nnov
            Z3JCb3RUZW5pUDVsdTYyTk1GS0o1bEZ4WXh3CnNxUTgybnhUbU81YzErdktqUFJa
            ajczMSs3b0hRWlFNS3loWkFUTzFhUXMKLS0tIGU0SkV0YldFTmlsTGlPWTEzQjNn
            WHlncVliTEVWd0dUUG5GUnptVzBlWlEKU7o8MTbGGkrInUkaL2fVOTK37TNVS7EM
            +q/TiLPewu0QR7r8TfWl+Q012JWt/tMwCyuLL8OgrQgsLYQqQ3WpuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T02:24:09Z"
    mac: ENC[AES256_GCM,data:RUgtTc2YHRKI0NopPN93fhqaYCEtnTeiRzuzjAsQ5lb+FrSjXLzc4ixpVDys+9DGKJBxf68PP5XkmZzUkYuCUdHYhsXSukeNICChJmBMFodUecnMEM6GwbKhduSwPfvBkL19Pf6pVuMqNtyGL7lQd5YjDvKQW/fl87Mlj/QHIqY=,iv:KlOXl2KfsnRx+J3yiJ3RttRf7cNOIzc33qf0rYW6Gq8=,tag:KFbFMNfV11ftk9LlqT2dHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
