apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:vQA3250EDr2HpNt0rA30hzHpqCi/paM=,iv:EcYRKpJ3le5wIKpAXG7OQR1Jgq1s9SZAbCLApz8UeJs=,tag:asHc4yA+/zEcXDY4nLrZZQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:pbblSzRnpBUYraCNP9P20G1ASO0fAvL2PdG7UMeC4mMIaEh7,iv:f1N+cisGNsAp4WIEknZ8wkZk0h3auMrWFBmNoICVKwQ=,tag:9xmJGdS92lCftDdZo55rDQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ohNipdC2vcLkL6R1guQ=,iv:1lxCCk+8GOTv6zyJxf3pQrAr67ZvKCde5E2kO2CcZjs=,tag:a5yNc+0eT0urhoNGFzir4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6T1NWRzNoRGI2VzJkMk5n
            WEFHTUNxaE9QYlBWRGNWVEpSSmxLc3U5eHd3CmdONlRkZ0JNdzYvUGpVUlNDa0ZD
            VTN3NmNDQlJycG94b0VEZldmaVVrS28KLS0tIHRkVUZwSlA2ampSNnN4UmsyajY2
            WnBVcjNUb1Q1TXFBZ2hKaVJUbmhRWGMK3CyHTNo/4RuuFf4P3u0djxHvrxoZ7K8m
            gmxZIYgUFzV+E0bi1TLmxuTchoiBzSjWfaUwPHNv5G4Yzy65JoS9yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T14:08:53Z"
    mac: ENC[AES256_GCM,data:+ql690iA4xCXzgxW/bqYk19Xdir8nvLkbKgoWco/K0C99NsP3GBjn5pPWuJ/kWxZtD1hcJY0Oce2z8zIDKtr0joVInQKZ5aLAQiaUu/n1HffItsitnOv0LBvTGIRmsyGQR20XMJPzsrrP5XwJ1fa/txvloIvCm5lzcUv+FSGYYw=,iv:JS6/eenGUGrBr0jNwHnJJGf/SzeppZg74bFaYs2r7/E=,tag:UYbbs0YWQu/qjEdcCcLkJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
