apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:yp+Ch+Jnr7u/bCJEPxO3GUJE8ZSrNuuQocAz,iv:8YOhlPs8dBh+KsehGmBP+8Xd/wds0o09xgi/C1LpSZY=,tag:aSUQ8Qrd9MMldyq7F+GV7Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Eq4nuNYDLVpTMdNbgkcUnyno7wvoIK7n9JjyzPTC33O2Cg9d,iv:MOk0JCUie1+4Twib1oS4PFvup01CYzDiQK7bqi8zGyg=,tag:VpgjNzOFtUQrVtQCIbPTJQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:13G4L9N6mL0dCDJmRKQ=,iv:oHImaTetOArY9y2Sz08/mpx3g4Z4AG8/QDcic7CoJCs=,tag:HxtKDmIhTzHHYjiOnDibsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeW1ZTEtrQytNWkhYaFBS
            a2hkZWNqN2hwSHdoMkxLTm5DOE91K3Q1UndJCjlVM1QyVGE4WjRraEFDWG9Sb1Qz
            MzBhWmw0RjRRYlhZbmptSEJFaG45YlEKLS0tIExBTlFuZnBMaTBrZGVpaXIxb2h4
            bC9OMFRtZ3E4dUZwMlRyUW90NWRESU0KJ3PGJVOKoxc4uRv8IwY7G8V89ptPDc4V
            BPA1tW+xxz4WXoV9BU3/3Zoas15TyeuHz/AF5jBMdtyxKCxYnR93Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T07:43:23Z"
    mac: ENC[AES256_GCM,data:qq6IbF46g/czx3NBqDDbKD0hhFeHfGMSm96Unp0rFrtB32umetqn1gZAs9/zcuBP6NtuAS0IBWKFjuRbkRW7LYAhV09G2PVjEHvzylqNvFJIXLetj6yX3Ktr0w1lAj4eeE0BJpNhMfc+R7xU/9u4VHdEA4tEeOnKIS85LFiFf4U=,iv:u3+eMg+rMd6QUsnrr9+qVjqsjedbDe3p6F7fwKWzYXw=,tag:9b/uUCTe8L4bzUB22EM1jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
