apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:2ibilA+SNrp+SQWo,iv:h3kfaF+Ibj7FgN836bA4jKgMuIbEAn3KJItf/+xP0Hs=,tag:FAshwwfM3DASre/fxjtVWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRGtVdDJHaHVkK01TYmlx
            WUJrb2JHS3V0M3h5YWkxRFNKdEZHL0QwbzJjCktZT3VsYTc3Uk1sUlg4NWtCR1dT
            bnVOeEpKS2xaNlhnSHpiWk5DTUp6dnMKLS0tIFJoUjdTMHdWdTBPYXB3RGRxTlo5
            UFNnS2k0T2RKM0EwWnB4Sk1hVVlJdTgKAx6mCn6YdwCHCQUtbexcuulN2+4Hk/6/
            QOzfFF404nFGRaOuwA7bpHf/ax+isCcuXX02i6q4znNnYDhA+UrPOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T09:42:38Z"
    mac: ENC[AES256_GCM,data:IGSB5lk0Kx+xpkLMBoyxMau5hi5JY5S2Ra5I1xPxd2N/LA0hYGy1i4WFQCIzmkxD4j6xGsYZhwOVc7u7Jx6OPF8ucdtshBz6PjiztzJokjJW7bnjlbqjJKTna6v4rnV1X4AX2UJUmTKq978F92g1RR26zFKaQplrCJPNEZxkrXY=,iv:bGnnSWbxbh5pFG1lkg1Xisa7WKC2gb6TFO+32iVMofg=,tag:WxxjRPLsNWckP0ku1gh5jA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
