apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:rhyQezdlUfnl6mMjyktZVr9zy3kkh9Q=,iv:qt2wIu27i0qQ+OmBcfO6Ue+kUGemfhgPBqvpw51wIDY=,tag:JtHlha/MROlvTF8O96VcQQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Wks4OjunaNMssD/FAaeBzi88lhX3ZC5lGzTIZG/xVqxX4/v6,iv:Qtp9L/eu1RLKTnlwI4n0fLMLiT3RdN9VZQYfldUt4AI=,tag:gwMxj26rvpZq4Ac+m9y5Zw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:/9FZhJ2bKELRKb8ceks=,iv:R0md0MAhIkYX7hd4FGCBWZpP4MIrMf3mjsC/RviKOG0=,tag:NcagEuOYc9mtxShe5l5rXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSlVlRWtUSmJtWHBCWUYx
            L0FmWnZ3eGJwWGdoQlUrTEJGODZON3VkY1VrCmxmRUlNRjduS1dmZEE4TWQrSktT
            N01YM2RuK3orRFZ3eXlyQlFRMlc4a1UKLS0tIGlsK01ra2FrSDZTMG5BSWxSSDFX
            M2NmTlUrZXp5QjZPdXBkb1NjZnVwUmcKebGmVs3NR13BuOa782TP3gUIp02Hpgl1
            8LQfJLeNi7qdGnSKK3mqRVpHv48usoVlL8dsgDsjEtNeUzPxno4/Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T07:30:12Z"
    mac: ENC[AES256_GCM,data:uysedgtAw1yX4EZ3qSAhjNTiPHKM7ZKTc0pWxqdB3bfSc4guRR2PAY1W9gRXi5W7GV0OJj5pGvn4ugdsbDgtxwRX2HTs9/2w4ETzDxET4diQVMSSp6tqUMdfKB0DzPvDsWyKEugpwfnQpZqsEdbPWVh0rvaaTYn1o57YUAuyiRU=,iv:/JUOgxsmwAlFiEJJ2rjytmt4p6XOzMkVBIMI/3Fk8Jk=,tag:XnLwqDdLvAskWgwW8SPu3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
