apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:Uq/qNY703TUOjFWb,iv:aAo8/l0Vj4lYW1dko1E+a09jgNhuX7rsgS4J7kxzKP8=,tag:2nHlzmzoNItqwPtIA5eZcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYTJXZTZML3NFSUJaSDlO
            RTdKR2FCR2tMK2ppekFYMlRJYng2OTBxbkNNCjZOWUNlejFCaXowcUFrY2xqalZB
            M3FiL3FuM1VKV0FQbGo1Sm1VVmh1NWMKLS0tIDNpbHpGSWdVeStDSTJnc3EvRThR
            Z1ZtcEIvK2ZndURmVTZMMk9IVDFiNWMKSfggZf6sAn0sle2DphQXI7ck+Gucpb/U
            ne1YEwlMZ29EkG+OiyOFzMaXBn9SKFLOVdhxfMOqoaL+IWtUizwjKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T11:06:01Z"
    mac: ENC[AES256_GCM,data:5+20/1usDmUyI4XCQR1uNsaB7oxQoQ+QmeKs4/uS+q6UNaCnE805vAjlnfaSu4rfQkWZ2jMaOLSYZf7qUjaeH+8VRt5SqhJ7jxlPwFLOp8B3V45/KGp+zrcHV8aTVF1mP7udyW5PyXWhIaU4nYso3GCVhhOoLUVFIm32ndozW0I=,iv:23qTBsrFuIDoe1MCX8nmElS2rIEhqrnubrdMRBhPxX8=,tag:gonBEx7zbjx/6brumGNoHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
