apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:OGp6lYLffnrT+IFq,iv:ZqMwUUZVHMmsNzDcgmj96zmDECeJ83NgP8LTsKa1GLM=,tag:g5SZKk861LSqaz2JnsyfkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdWE5Q2NGa1NDdnc3R0xJ
            eDlPbFh5WS9HdG9tVFZSeFMwa3lXNlJUSjNnCmlwU3d5cnE5ZjQ2UStsWEZieitR
            RVU4SHQxL05PWGx4RXhhVXlKWElCTTAKLS0tIEdmTTJLTStFZVhJa2crMERma0VM
            NHM3MDVkWnVJcjJ5Zy9heStxK0UweEUK9S9Wa3CqiFSGzKkac0CswJQvDNn3/5Iu
            C3jM/Nv17Lm5ZPqHdiGjTGLpE6fg0eKZiEZBvtjcIb/RVd7myP47IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-19T20:39:58Z"
    mac: ENC[AES256_GCM,data:u53ynesONH9raGQv/e+OYMN7xPL0V550ADYMa5GqMkQ2vsA8iFAfWV7IobVxsVzAkdSMOSxtNutBdXkejnOMmxT+uxAFjQHVmcQrLy7CM4sOFKOyBP/PSmyfsxu3nX3YHiQKmOSLZr726ahDWhO6eWy6InSUQyn+tgx9VFa8AiY=,iv:Mbiks+2z8ZD1tTsTfAlJ9pDPpzLPAxPm/JIJqHuxHa8=,tag:Ns6D98CQNVjunUj2DsZXVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
