apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:dcLhmjzDD+GpWWWU,iv:rxYnZr8u+FJkn65sysP3l4RQM/vsUntNUssAKqqazDA=,tag:8Pr7kItVa1iBUzLeX1y2ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL2ZCemRYYm1KNWlSTmZs
            MHcvVVJ0TlVOWkZKZ1BNMjkzR3p3VHRyRkVzClM4RnRDZndOTXA3S0gvYm9ZcmZR
            KzR0WVpvM0dvNG13ZkFCVk5PWk5RK2sKLS0tIFhwWjk4ckRLalMwQURPL3RUR2No
            MzFhWnhlVzFCWmN4L0cxdnpmMGJVd1UK3DWMcW1KG9wHaMVx8Sb1rG3UhrAmUL7v
            Rq4edkZJyFEnMyvzsRgvl3K7dBJc/gVPWb2Ew+GKO9zsEpImUd4ndA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T14:08:52Z"
    mac: ENC[AES256_GCM,data:4gCicazCzI2mPBFUaptQ2PDpb/OAxnXUwsUz131BvnKR/kU5LI/9zh8c6S2l6bYFoWCm3noxa35fZguB56GUEfhCfyoDyReLqmk1qDl8ClS6nzkGhKqSrq1HMNFmqUpsHXJFCFqn+g97MrVteaOqaSQBiS7XnAqRQULk6v95b8Q=,iv:4ugs/yW8ApBmfm8h7fWgC3Ly5c1u0jPL9NubaJGdgSY=,tag:/F03IXqCmCllx8bWtAOm1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
