apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ETFJeqDqJ8Dh+L+F04AkXCrSJsCVF7lTBtmy3+ynl0tOnH+f,iv:YA0Ae1MfiEu7cpbCGdcpV6K1K/SrVzxl5//Hy9q+4GU=,tag:A1C+eEtLXc3DjcgXRf0a/A==,type:str]
    credentials.json: ENC[AES256_GCM,data:27Vjo94VpgMGGeOfQPV+8pQDH6arDpi2LO7o7BIVRHeZDLRQ4L12wciJLomEJmEocwvmtBZDChOS+ZShTTexrvrCGVTerUoOCc8k5bQJnlyIE/Fgx/mNBhvSlCBUAa8LOiFTdp1620y5xYTmnBsQu2mXvkWkID+ub0J+LVdpDXIYC8NJWY6uMVd2thD5qLsyjxryqJrMkYT8ovntoytJkKL6ZJwRGS/eaChNnJ5c6w==,iv:jDduYk0WdFMMy/WRNhjgGsFiQI26h9O7PaD+oHFsOEY=,tag:EqfQ2vu0CF2leTHZw14OfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOFUyRnNJYmRaRWtnU1dL
            UU0rcytRUEU4b3dRU2pCckVabWk4Y0tOWGpzCnF1dG9LWFF0cHdsSGFObURTbkhk
            UFEvc1RHSmRMWW1IdXZwSnBhQmtsTDgKLS0tIHJILy9lNlFBWVRLbzZiRnVndWRu
            cmlWQUtTMDAwblNtcUswMEVGV0ozYUUKh1+VokS/HkQpQfWDQGUk/pboUlcidLQS
            xFQgtikjDBqp65fVFDMlIxGXr9kPWVvMsOp/WGrJF4Ss1qtNScuEhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T09:37:58Z"
    mac: ENC[AES256_GCM,data:wSZBG6Ex3eOaK7/AHT1BzS/mgqHHn9F9x9rQzfUTyE6WD/zgcb8tC5G274XPShU3Vi2hk1LJ4ES/KP5EyPZtnOBjPCZMyzjX/6Q2TGJGxHjXoCCYxjzfqKun5lQHRESHceOFxJ6wTxPKX70SNfg2xi6hN7E/s4NVCVuFScJ3uBk=,iv:3M8j8H2KljMHUdXJH3plXoIFLLBH65eC3Oc8F5RijaI=,tag:WCR83+GC2GSNDLfuRMqxSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
