apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:AEgTiPq6NlrHU9RnaKVFLqw1/XVdhukRV30DNRAqiGs0zadq,iv:QIBiuKSip+hUl59xw+IM1+8WRINlrT1AEWIMCWqxcrU=,tag:1ifr10EiGhG8Zdrl99oZWA==,type:str]
    credentials.json: ENC[AES256_GCM,data:gtbso8tYZCOHvPan7J+wCjRBm7PWVw/4hctDCQm3l20GIeaQmkjRyu6sEQJAZlhLVASIXn5DFarOaD+gpEj4G9OgkBAY3wqVXxVnFvxJ3Y+EiOvtI5Ky0UgecRched7NdQmKTt6718xG9VlLm5DJpsWJmDet74RPeaewBgqr/ipCq2/P8OIxzeKqCv9ZVr0LZegovJhmmamYrRJMz3SU+Oqj5xUHtvDUXzAKTA/gPw==,iv:VbP1K1fNehn0SQhUwRGyF+Tp6yTT2AD7Lv8oVXTXqPE=,tag:Xeyk0ojt0zGcrBa/v16fyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUnhnemJZNnJzSUU0c2gv
            YktzaWpCdGlsakhlMUZNOGVzb0NqKzQrTkhnCmZ3WmNldmk2cG55RUZndUFzTEpM
            c2pDQnBEbGlJdTBtamp0NFBZeHJTKzgKLS0tIEVMWUw1YWNKSE9DTnR3Z1ZoZ0I2
            M0lUYkRERXQzMjlSdFUyRkRhOXFSL2MKB1LMHrmda+idrFU4SNkzGMtbxoypxpR4
            F6gFIYVXT3gXJ4LEXG56weOck0q6NZyRkq8iklPpElcNxXtuF7lM8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-19T20:39:57Z"
    mac: ENC[AES256_GCM,data:DGq5TbojTZjYVt/bt4n+wFzRN5IIFS2adYs5Q9l/gtG6oUS4FA03G+5JypdhSOfAaSI8AG5IMmD4rxE5nH3fI1kMfH2d7e0FPyarVd7kBiV2np6l0Qq0BkOrzdkswfVi39W1ajRuq1BGLVp5HZm1adTsf2Wvr0I10Zx74uQIlk0=,iv:RyE2p93RFZwJYSgOz9eHz/hBny/Ciegy1jjXk0MKqKQ=,tag:kayQ/vYe3+/qd9B4ENIz/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
