apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:SpvMShBjns7MN8yA0Iwy75BayGhCHiqmniNTy9b6QyYVSGqU,iv:Wwk9ELGbDX1I7w4idSIZra9gnsWDFWDr/JZpVSEbFEc=,tag:GqDjMZTRW21+at5ppiYC5w==,type:str]
    credentials.json: ENC[AES256_GCM,data:Odfy6ptA6s5febFVMrpkJN/e6GoBFihUTPNPWJjEu+x8RSl1jROWP1WxbD++Zbf3zpkJHs+WmxlIabzSOFNxJB3foLhw+uyvTJQgn14QcFECpY47UWCsEQQE6Zw0TZ9au4xMX2pzOsENAGQLrCfosucgv822PXBghVeUyV1o2nXwnaBstF/C1EcoI6QDlp2ADUk7rvJFHyRQOblrOD8s1IsskYoUdvirY0uwgGomqA==,iv:1xSFyjWRiEt/fchjkiKQ8AkyNeLdhN3VvzPqE486TRQ=,tag:OjA57TUbUEcyX0RGdnsvzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age182pun7cjjdxeg7nn493a3q43854g3tmlzykhdzwtaeyhyt5qu9zsk5fr3p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTDRtbVpRcXozSFA0dkVO
            R2E0TmhyVFg0ZzJJRHEzNlhGc21tRzE4NEFvCnRwODB4WnkrT0h2ejljRTFsZFVj
            emlsbHU3SDZZT1Y4cVEwVUxZaS93NG8KLS0tIGlPcll1SUtKK3FTOHdYc1VnRzF1
            QmV6M2ZMcWhOb25UQ2hJQ1ZuWkhnWVUKzIHHdVyATIg+dz0OHUKU5TkpRo0eTLrN
            Fj1MnqgufcGtwdzfxj1gXfUNjck32NAIJm2jigApogGXQv2z76JMUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T10:32:11Z"
    mac: ENC[AES256_GCM,data:VO/9AxJ+ACIqcYuxLXZbTnKqi+BeVKEtWv8yu48Jx8fj7MiDjyOm8MH5TQbuRMywBIE1pb/gwDenhroLimooKRnSSnOj9zRE6TCG4OaGACI2y8iaFob5IJ6Q22f/UE/YEbDKBptiz9EUfX4laDhhM71K/aPF6qc836rW6YxKvqY=,iv:CMfnap/c9yQjOETRyhga29hZMEcimpUcVU+tVa5trbo=,tag:b1SipFSdoMcK26/4J59DCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
