---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn/longhorn
      version: 1.5.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    adminUser:
      create: true
      createSecret: false
      username: admin
    ingress:
      enabled: true
      className: internal
      annotations:
        hajimari.io/icon: sawtooth-wave
      hosts:
        - host: &host "longhorn.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    networkPolicy:
      create: false
    metrics:
      enabled: true
    rbac:
      create: true
      impersonationResourceNames: [ "admin" ]
    podAnnotations:
      secret.reloader.stakater.com/reload: cluster-user-auth
