---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: helix
spec:
  interval: 30m
  chart:
    spec:
        chart: vault
        sourceRef:
            kind: HelmRepository
            name: hashicorp
            namespace: flux-system
        version: 0.25.0
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
  values:
    global:
      # enabled is the master enabled switch. Setting this to true or false
      # will enable or disable all the components within this chart by default.
      enabled: true
      # The namespace to deploy to. Defaults to the `helm` installation namespace.
      namespace: helix
      # TLS for end-to-end encrypted transport
      tlsDisable: true
      # Create PodSecurityPolicy for pods
      psp:
        enable: false
        # Annotation for PodSecurityPolicy.
        # This is a multi-line templated string map, and can also be set as YAML.
        annotations: |
          seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default,runtime/default
          apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
          seccomp.security.alpha.kubernetes.io/defaultProfileName:  runtime/default
          apparmor.security.beta.kubernetes.io/defaultProfileName:  runtime/default
      serverTelemetry:
        # Enable integration with the Prometheus Operator
        # See the top level serverTelemetry section below before enabling this feature.
        prometheusOperator: false
